import { test,expect,type Page } from '@playwright/test';
import { mkdirSync } from 'node:fs';

test('station-first placement builds an oriented platform on open ground',async({page})=>{
  test.setTimeout(180000);
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',event=>{if(event.type()==='error'||event.type()==='warning')errors.push(event.text());});
  await page.goto('/');await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:'Start new company'}).click();await expect(page.locator('#main-menu')).toBeHidden();await page.evaluate(()=>window.__railProbe.regional());
  const before=await page.evaluate(()=>({revision:window.__railProbe.snapshot().railway.revision,terrainRevision:window.__railProbe.snapshot().operations.terrain.revision,stations:window.__railProbe.snapshot().stations.length}));
  await page.locator('#place-station').click();await page.getByLabel('Platform direction').fill('55');await expect(page.locator('#station-valid')).toContainText('Ready');mkdirSync('artifacts/evidence/con04',{recursive:true});await page.screenshot({path:'artifacts/evidence/station-first-preview.png'});await page.locator('#commit-station').click();await page.waitForFunction(count=>window.__railProbe?.snapshot().stations.length===count+1,before.stations);
  const after=await page.evaluate(()=>{const state=window.__railProbe.snapshot(),layout=state.stations[0]?.layout;return {revision:state.railway.revision,terrainRevision:state.operations.terrain.revision,terrainOperations:state.operations.terrain.operations.length,nodes:state.railway.nodes.length,edges:state.railway.edges.length,kind:layout?.kind,orientationRad:layout?.kind==='single-platform'?layout.orientationRad:null};});expect(after.revision).toBe(before.revision+1);expect(after.terrainRevision).toBe(before.terrainRevision+1);expect(after.terrainOperations).toBe(1);expect(after.nodes).toBe(3);expect(after.edges).toBe(2);expect(after.kind).toBe('single-platform');expect(after.orientationRad).toBeCloseTo(55*Math.PI/180);
  await page.locator('#place-station').click();await page.getByLabel('Platform direction').fill('55');await expect(page.locator('#station-valid')).toContainText('Ready');await page.locator('#commit-station').click();await page.waitForFunction(()=>window.__railProbe?.snapshot().stations.length===2);
  const route=await page.evaluate(()=>{const state=window.__railProbe.snapshot(),ports=state.stations.map((station,index)=>{if(station.layout.kind!=='single-platform')throw new Error('Expected platform station');const nodeId=station.layout.ports[index===0?1:0].nodeId;return state.railway.nodes.find(node=>node.id===nodeId)!.position;});return {ports,midpoint:{x:(ports[0]!.x+ports[1]!.x)/2,y:(ports[0]!.y+ports[1]!.y)/2,z:(ports[0]!.z+ports[1]!.z)/2}};});
  await page.getByRole('button',{name:'Overview'}).click();await page.getByRole('button',{name:'Build tracks'}).click();await expect(page.locator('#track-class option')).toHaveCount(3);await expect(page.getByLabel('Track standard')).toHaveValue('local');await page.getByLabel('Corridor').selectOption('free');await clickMap(page,route.ports[0]!);await clickMap(page,route.midpoint);await expect(page.locator('#alignment-steps')).toContainText('Shape the route');await expect(page.getByRole('button',{name:'Undo point'})).toBeEnabled();await page.getByRole('button',{name:'Undo point'}).click();await clickMap(page,route.ports[1]!);await expect(page.locator('#alignment-steps')).toContainText('Route ready');await expect(page.getByLabel('Recommended route')).toBeVisible();await expect(page.locator('#alternative-summary')).toContainText('structures');await expect(page.locator('#quote-valid')).toContainText('Feasible');const alternatives=await page.locator('#route-alternative option').count();expect(alternatives).toBeGreaterThanOrEqual(1);expect(alternatives).toBeLessThanOrEqual(3);expect(await page.evaluate(()=>window.__railProbe.planning())).toMatchObject({requests:1,accepted:1,pending:false});await expect(page.getByText('ENGINEERING PROFILE',{exact:true})).toBeVisible();await expect(page.locator('#engineering-metrics')).toContainText('Maximum grade');await expect(page.locator('#engineering-costs')).toContainText('Ground');mkdirSync('artifacts/evidence/con05',{recursive:true});await page.locator('#engineering-review').scrollIntoViewIfNeeded();await page.locator('#engineering-profile').hover({position:{x:180,y:55}});await page.screenshot({path:'artifacts/evidence/con05/engineering-review.png'});await page.getByRole('button',{name:'Build this alignment'}).click();await page.waitForFunction(()=>window.__railProbe?.snapshot().railway.edges.length===5);
  const committed=await page.evaluate(()=>({revision:window.__railProbe.snapshot().railway.revision,terrainRevision:window.__railProbe.snapshot().operations.terrain.revision,terrainOperations:window.__railProbe.snapshot().operations.terrain.operations.length,constructionEntries:window.__railProbe.snapshot().company.ledger.filter(entry=>entry.category==='construction').length,...window.__railProbe.stats()}));expect(committed).toMatchObject({revision:3,terrainRevision:3,terrainOperations:3,constructionEntries:3});expect(committed.terrainErrorM).toBeLessThan(.001);expect(committed.terrainPatchCells).toBeLessThan(2_000);expect(committed.terrainPatchTriangles).toBeLessThan(100_000);
  await page.evaluate(position=>window.__railProbe.focus(position),route.midpoint);await page.waitForTimeout(1200);const render=await page.evaluate(()=>window.__railProbe.stats());expect(render.terrainPatchCells).toBeLessThan(2_000);expect(render.terrainPatchTriangles).toBeLessThan(100_000);expect(render.contextLost).toBe(false);mkdirSync('artifacts/evidence/con04',{recursive:true});await page.screenshot({path:'artifacts/evidence/con04/engineered-alignment.png'});
  expect(errors).toEqual([]);
});

async function clickMap(page:Page,position:{x:number;y:number;z:number}):Promise<void>{const point=await page.evaluate(value=>window.__railProbe.project(value),position);expect(point.visible).toBe(true);await page.mouse.click(point.x,point.y);}
