import {expect,test} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';

test('replaces the current scene six times and remains responsive on desktop and mobile',async({page})=>{
  test.setTimeout(60_000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'||message.type()==='warning')errors.push(message.text());});await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext,seen=new WeakSet<object>();let count=0;Object.defineProperty(window,'__graphicsContextCount',{value:()=>count,configurable:true});HTMLCanvasElement.prototype.getContext=function(...args:Parameters<HTMLCanvasElement['getContext']>){const result=original.apply(this,args) as RenderingContext|null;if(result&&String(args[0]).startsWith('webgl')&&!seen.has(result)){seen.add(result);count++;}return result as never;};});
  await page.goto('/?skip-menu=1');await page.waitForFunction(()=>window.__railProbe?.ready===true);await page.evaluate(async()=>{window.__railProbe.setSpeed(0);await window.__railProbe.save();});const replacements:{source:'new'|'load';geometries:number;textures:number}[]=[];
  for(let index=0;index<6;index++){const source=index%2===0?'new':'load';if(source==='new'){await page.getByRole('button',{name:'Open main menu'}).click();await page.locator('#menu-settings-button').click();await page.locator('#choose-new-game').click();await page.getByRole('button',{name:/Start new company/}).click();}else await page.getByRole('button',{name:'Load study',exact:true}).click();await page.waitForFunction(expected=>{const snapshot=window.__railProbe.snapshot();return expected==='new'?snapshot.stations.length===0&&snapshot.trains.length===0:snapshot.stations.length===3&&snapshot.trains.length===1;},source);await page.evaluate(()=>{window.__railProbe.setSpeed(0);window.__railProbe.regional();});await page.waitForTimeout(500);const stats=await page.evaluate(()=>window.__railProbe.stats());replacements.push({source,geometries:stats.geometries,textures:stats.textures});}
  const spread=(values:number[])=>Math.max(...values)-Math.min(...values),bySource=(source:'new'|'load',key:'geometries'|'textures')=>replacements.filter(item=>item.source===source).map(item=>item[key]),newGeometries=bySource('new','geometries'),loadGeometries=bySource('load','geometries');expect(newGeometries).toHaveLength(3);expect(loadGeometries).toHaveLength(3);expect(spread(newGeometries)).toBeLessThanOrEqual(3);expect(spread(loadGeometries)).toBeLessThanOrEqual(3);expect(spread(bySource('new','textures'))).toBeLessThanOrEqual(1);expect(spread(bySource('load','textures'))).toBeLessThanOrEqual(1);expect(Math.max(...replacements.map(item=>item.geometries))).toBeLessThanOrEqual(240);expect(await page.evaluate(()=>(window as unknown as {__graphicsContextCount():number}).__graphicsContextCount())).toBe(1);await page.evaluate(()=>window.__railProbe.resetMetrics());await page.waitForTimeout(1200);const frameCount=await page.evaluate(()=>window.__railProbe.metrics().frames.length);expect(frameCount).toBeGreaterThan(45);expect(frameCount).toBeLessThan(100);
  mkdirSync('artifacts/evidence/gfx-008',{recursive:true});await page.screenshot({path:'artifacts/evidence/gfx-008/desktop.png'});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);const layout=await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,canvas:document.querySelector('#world')!.getBoundingClientRect().toJSON()}));expect(layout.scrollWidth).toBeLessThanOrEqual(layout.innerWidth+1);await expect(page.getByRole('button',{name:'Overview'})).toBeVisible();await page.screenshot({path:'artifacts/evidence/gfx-008/mobile.png',fullPage:true});expect(errors).toEqual([]);writeFileSync('artifacts/evidence/gfx-008/session-replacement.json',JSON.stringify({replacements,contextCount:1,frameCount,layout},null,2));
  await page.evaluate(()=>window.__railProbe.dispose());const disposed=await page.evaluate(()=>window.__railProbe.stats());expect(disposed.geometries).toBe(0);expect(disposed.contextLost).toBe(true);
});
