import {expect,test} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';

test('replaces V1 and V3 scenes five times and remains responsive on desktop and mobile',async({page})=>{
  test.setTimeout(60_000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'||message.type()==='warning')errors.push(message.text());});await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext,seen=new WeakSet<object>();let count=0;Object.defineProperty(window,'__graphicsContextCount',{value:()=>count,configurable:true});HTMLCanvasElement.prototype.getContext=function(...args:Parameters<HTMLCanvasElement['getContext']>){const result=original.apply(this,args) as RenderingContext|null;if(result&&String(args[0]).startsWith('webgl')&&!seen.has(result)){seen.add(result);count++;}return result as never;};});
  await page.goto('/?skip-menu=1&world=v1');await page.waitForFunction(()=>window.__railProbe?.ready===true);await page.evaluate(async()=>{window.__railProbe.setSpeed(0);await window.__railProbe.save();});const replacements:{version:number;geometries:number;textures:number}[]=[];
  for(let index=0;index<5;index++){const nextVersion=index%2===0?3:1;if(nextVersion===3){await page.getByRole('button',{name:'Open main menu'}).click();await page.getByRole('button',{name:/Start new company/}).click();}else await page.getByRole('button',{name:'Load study',exact:true}).click();await page.waitForFunction(version=>window.__railProbe.snapshot().world.generatorVersion===version,nextVersion);await page.evaluate(()=>{window.__railProbe.setSpeed(0);window.__railProbe.regional();});await page.waitForTimeout(500);const stats=await page.evaluate(()=>window.__railProbe.stats());replacements.push({version:nextVersion,geometries:stats.geometries,textures:stats.textures});}
  const values=(version:number,key:'geometries'|'textures')=>new Set(replacements.filter(item=>item.version===version).map(item=>item[key])).size;expect(values(1,'geometries')).toBe(1);expect(values(3,'geometries')).toBe(1);expect(values(1,'textures')).toBe(1);expect(values(3,'textures')).toBe(1);expect(await page.evaluate(()=>(window as unknown as {__graphicsContextCount():number}).__graphicsContextCount())).toBe(1);await page.evaluate(()=>window.__railProbe.resetMetrics());await page.waitForTimeout(1200);const frameCount=await page.evaluate(()=>window.__railProbe.metrics().frames.length);expect(frameCount).toBeGreaterThan(45);expect(frameCount).toBeLessThan(100);
  mkdirSync('artifacts/evidence/gfx-008',{recursive:true});await page.screenshot({path:'artifacts/evidence/gfx-008/desktop.png'});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);const layout=await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,canvas:document.querySelector('#world')!.getBoundingClientRect().toJSON()}));expect(layout.scrollWidth).toBeLessThanOrEqual(layout.innerWidth+1);await expect(page.getByRole('button',{name:'Overview'})).toBeVisible();await page.screenshot({path:'artifacts/evidence/gfx-008/mobile.png',fullPage:true});expect(errors).toEqual([]);writeFileSync('artifacts/evidence/gfx-008/session-replacement.json',JSON.stringify({replacements,contextCount:1,frameCount,layout},null,2));
  await page.evaluate(()=>window.__railProbe.dispose());const disposed=await page.evaluate(()=>window.__railProbe.stats());expect(disposed.geometries).toBe(0);expect(disposed.contextLost).toBe(true);
});
