import {expect,test} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';

test('renders detailed current Norway rolling stock from four inspection views',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'||message.type()==='warning')errors.push(message.text());});await page.goto('/?skip-menu=1');await page.waitForFunction(()=>window.__railProbe?.ready===true);await page.evaluate(()=>window.__railProbe.setSpeed(0));
  const assets=await page.evaluate(()=>window.__railProbe.assets),locomotive=assets.find(asset=>asset.name==='nord-2-6-0'&&asset.lod===0),coach=assets.find(asset=>asset.name==='fjord-passenger-coach'&&asset.lod===0),freight=assets.find(asset=>asset.name==='fjord-freight-wagon'&&asset.lod===0);expect(locomotive?.triangles).toBe(1204);expect(coach?.triangles).toBe(536);expect(freight?.triangles).toBe(452);
  await page.getByRole('button',{name:'Operations'}).click();const freightStation=await page.evaluate(()=>window.__railProbe.snapshot().stations.find(station=>station.townId==='town:3')!.id);await page.locator('#purchase-station').selectOption(freightStation);await page.locator('#consist-kind').selectOption('freight');await page.locator('#coach-count').selectOption('1');await page.getByRole('button',{name:'Buy consist'}).click();await page.getByRole('button',{name:'Close railway operations'}).click();await page.waitForFunction(()=>window.__railProbe.stats().trains===2);
  mkdirSync('artifacts/evidence/gfx-006b',{recursive:true});const canvas=page.locator('#world'),vehicleIds=['nord-2-6-0','fjord-passenger-coach','fjord-freight-wagon'];for(const assetId of vehicleIds)for(const view of ['front','left','right','roof'] as const){await page.evaluate(([value,id])=>window.__railProbe.vehicleInspection(value as 'front'|'left'|'right'|'roof',id),[view,assetId]);await page.waitForTimeout(220);await canvas.screenshot({path:`artifacts/evidence/gfx-006b/${assetId}-${view}.png`});}
  const state=await page.evaluate(()=>window.__railProbe.snapshot()),stats=await page.evaluate(()=>window.__railProbe.stats());expect(state.trains[0]?.locomotiveId).toBe('nord-2-6-0');expect(state.trains[0]?.vehicleIds).toEqual(['fjord-passenger-coach','fjord-passenger-coach']);expect(state.trains.some(train=>train.vehicleIds.includes('fjord-freight-wagon'))).toBe(true);expect(stats.textures).toBeGreaterThanOrEqual(18);expect(errors).toEqual([]);writeFileSync('artifacts/evidence/gfx-006b/runtime.json',JSON.stringify({locomotive,coach,freight,stats},null,2));
});
