import {expect,test} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';

const percentile=(values:number[],fraction:number)=>[...values].sort((a,b)=>a-b)[Math.min(values.length-1,Math.floor(values.length*fraction))]??Infinity;

test('keeps the composed Norway camera path and scale fixture within the graphics budgets',async({page})=>{
  test.setTimeout(100_000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'||message.type()==='warning')errors.push(message.text());});await page.goto('/?skip-menu=1');await page.waitForFunction(()=>window.__railProbe?.ready===true);await page.evaluate(()=>{window.__railProbe.setSpeed(1);window.__railProbe.resetMetrics();});
  const sweep=await page.evaluate(async()=>{const probe=window.__railProbe,start=performance.now(),samples:{elapsedMs:number;calls:number;triangles:number}[]=[],nextSample={value:0};let one=probe.metrics(),switched=false;while(performance.now()-start<60_000){const elapsed=performance.now()-start;if(!switched&&elapsed>=30_000){one=probe.metrics();probe.setSpeed(8);probe.resetMetrics();switched=true;}probe.cameraSweep((elapsed%30_000)/30_000);if(elapsed>=nextSample.value){const stats=probe.stats();samples.push({elapsedMs:elapsed,calls:stats.calls,triangles:stats.triangles});nextSample.value+=250;}await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));}return {one,eight:probe.metrics(),samples};});
  const summarize=(metrics:typeof sweep.one)=>({samples:metrics.frames.length,frameP50Ms:percentile(metrics.frames,.5),frameP95Ms:percentile(metrics.frames,.95),renderP95Ms:percentile(metrics.renderMs,.95),tickP95Ms:percentile(metrics.tickMs,.95)}),one=summarize(sweep.one),eight=summarize(sweep.eight);expect(one.samples).toBeGreaterThan(900);expect(eight.samples).toBeGreaterThan(900);expect(one.frameP95Ms).toBeLessThan(33.3);expect(eight.frameP95Ms).toBeLessThan(33.3);expect(Math.max(...sweep.samples.map(item=>item.calls))).toBeLessThanOrEqual(300);
  mkdirSync('artifacts/evidence/gfx-007',{recursive:true});const views:Record<string,unknown>={};for(const id of ['regional','shore','forest-edge','train'] as const){if(id==='train')await page.evaluate(()=>window.__railProbe.focusTrain());else await page.evaluate(value=>window.__railProbe.cameraPreset(value),id);await page.waitForTimeout(300);views[id]=await page.evaluate(()=>window.__railProbe.stats());await page.screenshot({path:`artifacts/evidence/gfx-007/${id}.png`});expect((views[id] as {calls:number}).calls).toBeLessThanOrEqual(300);expect((views[id] as {triangles:number}).triangles).toBeLessThanOrEqual(2_000_000);}
  await page.evaluate(()=>{window.__railProbe.setStress(true);window.__railProbe.setSpeed(8);});await page.waitForFunction(()=>window.__railProbe.metrics().frames.length>=300,null,{timeout:15_000});const stress=await page.evaluate(()=>window.__railProbe.metrics()),stressSummary=summarize(stress);expect(stress.calls).toBeLessThanOrEqual(450);expect(stressSummary.frameP95Ms).toBeLessThan(33.3);expect(errors).toEqual([]);writeFileSync('artifacts/evidence/gfx-007/runtime.json',JSON.stringify({one,eight,sweepMax:{calls:Math.max(...sweep.samples.map(item=>item.calls)),triangles:Math.max(...sweep.samples.map(item=>item.triangles))},views,stress:{...stressSummary,calls:stress.calls,triangles:stress.triangles,geometries:stress.geometries,textures:stress.textures},environment:{userAgent:stress.userAgent,viewport:stress.viewport,dpr:stress.dpr}},null,2));
});
