import { test,expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';

test('office UI upgrades a station, purchases a consist, creates a route and assigns service',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',event=>{if(event.type()==='error'||event.type()==='warning')errors.push(event.text());});
  await page.goto('/?skip-menu=1');await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:'Trains & lines'}).click();await expect(page.getByRole('region',{name:'Railway operations'})).toBeVisible();
  await expect(page.getByText('COMPANY REPORT')).toBeVisible();await expect(page.locator('#company-report')).toContainText('Company value');await expect(page.locator('#company-report')).toContainText('Operating result');await expect(page.locator('#month-heading')).toHaveText(/MONTH \d+/);await expect(page.locator('#ledger-summary')).toContainText('Result');
  const stations=await page.evaluate(()=>window.__railProbe.snapshot().stations.map(station=>station.id));await page.locator('#upgrade-station-id').selectOption(stations[0]!);await page.locator('#upgrade-class-id').selectOption('small-station');await page.getByRole('button',{name:'Upgrade station'}).click();await expect(page.locator('#operations-valid')).toContainText('Small Station');expect(await page.evaluate(id=>window.__railProbe.snapshot().stations.find(station=>station.id===id)?.classId,stations[0]!)).toBe('small-station');
  await page.getByLabel('Purchase at').selectOption(stations[0]!);await page.getByLabel('Cars').selectOption('2');await page.getByRole('button',{name:'Buy consist'}).click();await expect(page.locator('#operations-valid')).toContainText('purchased');
  const trainId=await page.evaluate(()=>window.__railProbe.snapshot().trains.at(-1)!.id);expect(await page.evaluate(()=>window.__railProbe.snapshot().trains.length)).toBe(2);await expect(page.getByText('Train purchase')).toBeVisible();
  for(const station of stations){await page.getByLabel('Next ordered stop').selectOption(station);await page.getByRole('button',{name:'Add stop'}).click();}await page.getByLabel('Service pattern').selectOption('loop');await page.getByRole('button',{name:'Create route'}).click();await expect(page.locator('#operations-valid')).toContainText('Loop route created');
  const routeId=await page.evaluate(()=>window.__railProbe.snapshot().routes.at(-1)!.id);await page.locator('#electrify-route-id').selectOption(routeId);await page.getByRole('button',{name:'Build overhead line'}).click();await expect(page.locator('#operations-valid')).toContainText('electrified');expect(await page.evaluate(()=>window.__railProbe.snapshot().company.ledger.some(entry=>entry.description==='Route electrification'))).toBe(true);expect(await page.evaluate(()=>Object.values(window.__railProbe.snapshot().operations.infrastructure).filter(item=>item.electrified).length)).toBeGreaterThan(0);
  await page.locator('#assign-train').selectOption(trainId);await page.locator('#assign-route-select').selectOption(routeId);await page.getByRole('button',{name:'Assign service'}).click();await expect(page.locator('#operations-valid')).toContainText('assigned');
  expect(await page.evaluate(id=>window.__railProbe.snapshot().trains.find(train=>train.id===id)?.routeId,trainId)).toBe(routeId);expect(await page.evaluate(id=>window.__railProbe.snapshot().routes.find(route=>route.id===id)?.mode,routeId)).toBe('loop');expect(['running','blocked']).toContain(await page.evaluate(id=>window.__railProbe.snapshot().trains.find(train=>train.id===id)?.phase,trainId));const routeRow=page.locator('#route-roster>div').filter({hasText:routeId.replace(':',' ')});await expect(routeRow).toContainText('↻');await expect(routeRow).toContainText('electrified');await expect(routeRow).toContainText('revenue');await expect(routeRow).toContainText('cost');await expect(routeRow).toContainText('result');await page.waitForFunction(()=>window.__railProbe.stats().trains===2);mkdirSync('artifacts/evidence',{recursive:true});await page.screenshot({path:'artifacts/evidence/operations-office.png'});await page.locator('#company-report').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/evidence/company-report.png'});await page.getByRole('button',{name:'Close railway operations'}).click();await page.getByRole('button',{name:'Follow train'}).click();await page.getByRole('button',{name:'Pause'}).click();await page.waitForTimeout(300);await page.screenshot({path:'artifacts/evidence/route-electrification.png'});expect(errors).toEqual([]);
});
