import { test,expect,type Page } from '@playwright/test';
import { mkdirSync } from 'node:fs';

test('empty Norway charter reaches saved passenger revenue through the UI',async({page})=>{
  test.setTimeout(150000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',event=>{if(event.type()==='error'||event.type()==='warning')errors.push(event.text());});
  await page.goto('/');await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:/Start new company/}).click();await page.getByRole('button',{name:'Pause',exact:true}).click();
  expect(await page.evaluate(()=>{const state=window.__railProbe.snapshot();return [state.railway.edges.length,state.stations.length,state.trains.length,state.towns.length];})).toEqual([0,0,0,3]);await page.getByRole('navigation',{name:'Focus a settlement'}).getByRole('button',{name:/Sundvik/}).click();await page.getByRole('button',{name:'Regional view'}).click();
  const towns=await page.evaluate(()=>window.__railProbe.snapshot().towns.slice(0,2).map(town=>town.position));
  await page.getByRole('button',{name:'Survey track'}).click();await page.getByLabel('Corridor').selectOption('free');for(const town of towns)await clickMap(page,town);
  await expect(page.locator('#quote-valid')).toContainText('Feasible');await page.getByRole('button',{name:'Build this alignment'}).click();await page.waitForFunction(()=>window.__railProbe.snapshot().railway.edges.length===1);
  const nodes=await page.evaluate(()=>window.__railProbe.snapshot().railway.nodes.map(node=>node.position));for(const node of nodes){await page.getByRole('button',{name:'Place station'}).click();await clickMap(page,node);await expect(page.locator('#station-valid')).toContainText('Ready');await page.getByRole('button',{name:'Build station'}).click();}
  expect(await page.evaluate(()=>window.__railProbe.snapshot().stations.length)).toBe(2);
  await page.getByRole('button',{name:'Operations'}).click();const stations=await page.evaluate(()=>window.__railProbe.snapshot().stations.map(station=>station.id));await page.locator('#purchase-station').selectOption(stations[0]!);await page.getByRole('button',{name:'Buy steam consist'}).click();
  const trainId=await page.evaluate(()=>window.__railProbe.snapshot().trains[0]!.id);await page.locator('#route-from').selectOption(stations[0]!);await page.locator('#route-to').selectOption(stations[1]!);await page.getByRole('button',{name:'Create shuttle route'}).click();const routeId=await page.evaluate(()=>window.__railProbe.snapshot().routes[0]!.id);await page.locator('#assign-train').selectOption(trainId);await page.locator('#assign-route-select').selectOption(routeId);await page.getByRole('button',{name:'Assign service'}).click();await page.getByRole('button',{name:'Close railway operations'}).click();
  await page.getByRole('button',{name:'8×',exact:true}).click();await page.waitForFunction(()=>window.__railProbe.snapshot().operations.delivered.passengers>0,null,{timeout:110000});await page.getByRole('button',{name:'Pause',exact:true}).click();
  const saved=await page.evaluate(()=>window.__railProbe.snapshot());expect(saved.company.ledger.some(entry=>entry.category==='passenger')).toBe(true);expect(saved.company.ledger.some(entry=>entry.category==='maintenance')).toBe(true);expect(saved.operations.delivered.passengers).toBeGreaterThan(0);expect(saved.company.cash).toBe(saved.company.openingCash+saved.company.ledger.reduce((sum,entry)=>sum+entry.amount,0));mkdirSync('artifacts/evidence',{recursive:true});await page.screenshot({path:'artifacts/evidence/passenger-milestone.png'});
  await page.getByRole('button',{name:'Save study'}).click();await expect(page.getByRole('status')).toContainText('Study saved');await page.reload();await page.waitForFunction(()=>window.__railProbe?.ready);await expect(page.getByRole('button',{name:'Continue latest'})).toBeEnabled();await page.getByRole('button',{name:'Continue latest'}).click();
  await expect(page.getByRole('region',{name:'Main menu'})).toBeHidden();expect(await page.evaluate(()=>window.__railProbe.snapshot())).toEqual(saved);await page.getByRole('button',{name:'1×',exact:true}).click();await page.waitForFunction(tick=>window.__railProbe.snapshot().tick>tick+5,saved.tick);expect(errors).toEqual([]);
});

async function clickMap(page:Page,position:{x:number;y:number;z:number}):Promise<void>{const point=await page.evaluate(value=>window.__railProbe.project(value),position);expect(point.visible).toBe(true);await page.mouse.click(point.x,point.y);}
