import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';

test('a constructed railway continues through a saved real train to an operating service',async({page})=>{
 test.setTimeout(120000);page.setDefaultTimeout(20000);await page.setViewportSize({width:1280,height:720});const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/?draw-practice=1&lang=de');await expect(page.locator('#planner')).toBeVisible({timeout:30000});await page.locator('#route-ports button').first().click();await page.locator('#route-ports button').first().click();await expect(page.locator('#commit-track')).toBeEnabled();await page.locator('#commit-track').click();
 const action=page.locator('#practice-service-action');await expect(action).toHaveText('Zug zusammenstellen');await expect(page.locator('#practice-service-note')).toContainText('erschließen Orte');
 const card=await page.locator('#practice-progress').boundingBox();expect(card!.y).toBeGreaterThan(70);expect(card!.y+card!.height).toBeLessThan(570);
 const before=await page.evaluate(()=>window.__railProbe.snapshot());await action.click();await expect(page.locator('#practice-progress')).toBeHidden();expect(await page.evaluate(()=>window.__railProbe.snapshot().company.cash)).toBe(before.company.cash);await expect(page.locator('#route-draft li')).toHaveCount(2);
 await page.locator('#purchase-train .office-action').click();await expect(page.locator('#create-route-action')).toBeFocused();const bought=await page.evaluate(()=>window.__railProbe.snapshot());expect(bought.trains).toHaveLength(1);expect(bought.company.cash).toBeLessThan(before.company.cash);
 await page.locator('#close-operations').click();await expect(action).toHaveText('Halte festlegen');await page.evaluate(()=>window.__railProbe.save());
 // Load this same company without query-driven creation of another practice.
 await page.goto('/?lang=de');await page.waitForFunction(()=>window.__railProbe?.ready);await page.locator('#continue-game').click();await expect(action).toHaveText('Halte festlegen');await action.click();await expect(page.locator('#route-draft li')).toHaveCount(2);await page.locator('#create-route-action').click();await expect(page.locator('#assign-route .office-action')).toBeFocused();
 await page.locator('#close-operations').click();await expect(action).toHaveText('Linie zuweisen');await action.click();await page.locator('#assign-route .office-action').click();await expect(page.locator('#follow-service')).toBeFocused();await page.locator('#close-operations').click();await expect(action).toHaveText('Zeit fortsetzen und Zug folgen');
 const assigned=await page.evaluate(()=>window.__railProbe.snapshot());expect(assigned.trains).toHaveLength(1);expect(assigned.routes).toHaveLength(1);expect(assigned.company.cash).toBe(bought.company.cash);expect(assigned.railway).toEqual(bought.railway);
 await action.click();await page.waitForFunction(tick=>window.__railProbe.snapshot().tick>tick+30,assigned.tick);await expect(action).toHaveText('Diesen Zug begleiten');expect(await page.evaluate(()=>window.__railProbe.snapshot().operations.trainServices[window.__railProbe.snapshot().trains[0]!.id]!.distanceM)).toBeGreaterThan(0);
 await page.evaluate(()=>window.__railProbe.setSpeed(0));await expect(action).toHaveText('Zeit fortsetzen und Zug folgen');mkdirSync('artifacts/evidence/practice-service',{recursive:true});await page.screenshot({path:'artifacts/evidence/practice-service/first-train.png'});expect(errors).toEqual([]);
});

test('remote construction stops explain test running instead of promising passengers',async({page})=>{
 page.setDefaultTimeout(20000);await page.setViewportSize({width:390,height:844});await page.goto('/?draw-practice=1&lesson=highland&lang=en');await expect(page.locator('#planner')).toBeVisible({timeout:30000});await page.locator('#route-ports button').first().click();await page.locator('#route-ports button').first().click();await expect(page.locator('#commit-track')).toBeEnabled();await page.locator('#commit-track').click();await expect(page.locator('#practice-service-action')).toHaveText('Assemble a train');await expect(page.locator('#practice-service-note')).toContainText('outside town catchments');await expect(page.locator('#follow')).toBeHidden();const bounds=await page.locator('#practice-service-action').boundingBox();expect(bounds!.y).toBeGreaterThan(80);const cameraControls=await page.locator('.view-controls').boundingBox();expect(bounds!.y+bounds!.height).toBeLessThan(cameraControls!.y-8);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
