import {test,expect} from '@playwright/test';

test('introduction can be dismissed without changing the company and remains dismissed after reload',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',event=>{if(event.type()==='error'||event.type()==='warning')errors.push(event.text());});
  await page.goto('/');await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:/Start new company/}).click();await expect(page.locator('#tutorial-card')).toBeVisible();const before=await page.evaluate(()=>({cash:window.__railProbe.snapshot().company.cash,stations:window.__railProbe.snapshot().stations.length}));await page.getByRole('button',{name:'End introduction'}).click();await expect(page.locator('#tutorial-card')).toBeHidden();expect(await page.evaluate(()=>window.__railProbe.snapshot().learning?.status)).toBe('dismissed');expect(await page.evaluate(()=>({cash:window.__railProbe.snapshot().company.cash,stations:window.__railProbe.snapshot().stations.length}))).toEqual(before);
  await page.getByRole('button',{name:'Save study'}).click();await expect(page.getByRole('status')).toContainText('Study saved');await page.reload();await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:'Continue latest'}).click();await expect(page.getByRole('region',{name:'Main menu'})).toBeHidden();await expect(page.locator('#tutorial-card')).toBeHidden();expect(await page.evaluate(()=>window.__railProbe.snapshot().learning?.status)).toBe('dismissed');expect(errors).toEqual([]);
});

test('free play starts with every tool available and no tutorial state',async({page})=>{
  await page.goto('/');await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:'Free play'}).click();await expect(page.getByRole('region',{name:'Main menu'})).toBeHidden();await expect(page.locator('#tutorial-card')).toBeHidden();expect(await page.evaluate(()=>window.__railProbe.snapshot().learning)).toBeNull();await expect(page.getByRole('button',{name:'Build station'})).toBeEnabled();await expect(page.getByRole('button',{name:'Build tracks'})).toBeEnabled();await expect(page.getByRole('button',{name:'Trains & lines'})).toBeEnabled();
});

test('an active introduction resumes at the first unmet real action',async({page})=>{
  test.setTimeout(90000);await page.goto('/');await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:/Start new company/}).click();await page.locator('#place-station').click();await page.getByLabel('Platform direction').fill('55');await expect(page.locator('#station-valid')).toContainText('Ready');await page.locator('#commit-station').click();await expect(page.locator('#tutorial-step')).toHaveText('STEP 2 OF 7');const stationId=await page.evaluate(()=>window.__railProbe.snapshot().learning?.bound.stationIds[0]);await page.getByRole('button',{name:'Save study'}).click();await expect(page.getByRole('status')).toContainText('Study saved');await page.reload();await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:'Continue latest'}).click();await expect(page.locator('#tutorial-step')).toHaveText('STEP 2 OF 7');expect(await page.evaluate(()=>window.__railProbe.snapshot().learning?.bound.stationIds[0])).toBe(stationId);expect(await page.evaluate(()=>window.__railProbe.snapshot().stations.length)).toBe(1);
});

test('repeating the introduction creates a named practice slot and preserves the current company',async({page})=>{
  await page.goto('/');await page.waitForFunction(()=>window.__railProbe?.ready);await page.getByRole('button',{name:'Free play'}).click();await page.getByRole('button',{name:'Open main menu'}).click();await page.getByRole('button',{name:'Settings'}).click();await page.getByRole('button',{name:'Start practice company'}).click();await expect(page.getByRole('region',{name:'Main menu'})).toBeHidden();await expect(page.locator('#tutorial-step')).toHaveText('STEP 1 OF 7');expect(await page.evaluate(()=>window.__railProbe.snapshot().learning?.status)).toBe('active');await page.getByRole('button',{name:'Open main menu'}).click();await page.getByRole('button',{name:'Load game'}).click();await expect(page.getByText('Company before introduction · Day 1')).toBeVisible();await expect(page.getByText('Introduction practice · Day 1')).toBeVisible();
});
